name: ğŸš¢ Deploy

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    steps:
      - name: ğŸ“¥ Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: master

      - name: ğŸ’» Node setup
        uses: ./.github/actions/node-setup

      - name: ğŸ‘ï¸â€ğŸ—¨ï¸ Static Code Analysis
        uses: ./.github/actions/static-code-analysis

      - name: ğŸš© Get version from package.json
        run: |
          echo "PACKAGE_VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: ğŸ Create Git Tag
        run: |
          git tag $PACKAGE_VERSION
          git push origin $PACKAGE_VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸš¢ Publish
        run: pnpm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
